In [135]:
import pandas as pd

In [136]:
df = pd.read_csv('NIFTY 50 - first 45 minutes data 2015 to Aug 2024.csv')
df.index = pd.to_datetime(df['date'])

In [137]:
df

,year,month,day,date,date.1,open,high,low,close,volume,...,day_name,max,min,difference,candle_body,high_shadow,low_shadow,low-open,high-open,trend
date,,,,,,,,,,,,,,,,,,,,,
2015-01-09 09:15:00+05:30,2015,1,9,2015-01-09 09:15:00+05:30,2015-01-09 09:15:00+05:30,8285.45,8295.90,8285.45,8292.10,0,...,Friday,8295.90,8285.45,10.45,-6.65,3.80,0.00,0.00,10.45,DOWN
2015-01-09 09:16:00+05:30,2015,1,9,2015-01-09 09:16:00+05:30,2015-01-09 09:16:00+05:30,8292.60,8293.60,8287.20,8288.15,0,...,Friday,8293.60,8287.20,6.40,4.45,1.00,-0.95,-5.40,1.00,UP
2015-01-09 09:17:00+05:30,2015,1,9,2015-01-09 09:17:00+05:30,2015-01-09 09:17:00+05:30,8287.40,8293.90,8287.40,8293.90,0,...,Friday,8293.90,8287.40,6.50,-6.50,0.00,0.00,0.00,6.50,DOWN
2015-01-09 09:18:00+05:30,2015,1,9,2015-01-09 09:18:00+05:30,2015-01-09 09:18:00+05:30,8294.25,8300.65,8293.90,8300.65,0,...,Friday,8300.65,8293.90,6.75,-6.40,0.00,-0.35,-0.35,6.40,DOWN
2015-01-09 09:19:00+05:30,2015,1,9,2015-01-09 09:19:00+05:30,2015-01-09 09:19:00+05:30,8300.60,8301.30,8298.75,8301.20,0,...,Friday,8301.30,8298.75,2.55,-0.60,0.10,-1.85,-1.85,0.70,DOWN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-28 09:55:00+05:30,2024,8,28,2024-08-28 09:55:00+05:30,2024-08-28 09:55:00+05:30,25015.30,25021.85,25013.00,25017.10,0,...,Wednesday,25021.85,25013.00,8.85,-1.80,4.75,-2.30,-2.30,6.55,DOWN
2024-08-28 09:56:00+05:30,2024,8,28,2024-08-28 09:56:00+05:30,2024-08-28 09:56:00+05:30,25016.60,25017.05,25008.50,25009.85,0,...,Wednesday,25017.05,25008.50,8.55,6.75,0.45,-1.35,-8.10,0.45,UP
2024-08-28 09:57:00+05:30,2024,8,28,2024-08-28 09:57:00+05:30,2024-08-28 09:57:00+05:30,25010.20,25012.55,25008.55,25009.70,0,...,Wednesday,25012.55,25008.55,4.00,0.50,2.35,-1.15,-1.65,2.35,UP
2024-08-28 09:58:00+05:30,2024,8,28,2024-08-28 09:58:00+05:30,2024-08-28 09:58:00+05:30,25009.95,25021.35,25009.05,25018.50,0,...,Wednesday,25021.35,25009.05,12.30,-8.55,2.85,-0.90,-0.90,11.40,DOWN
2024-08-28 09:59:00+05:30,2024,8,28,2024-08-28 09:59:00+05:30,2024-08-28 09:59:00+05:30,25017.90,25025.75,25017.05,25023.10,0,...,Wednesday,25025.75,25017.05,8.70,-5.20,2.65,-0.85,-0.85,7.85,DOWN

In [138]:
df = df[(df['year'] == 2024) & ~((df['hour'] == 9) & (df['minute'] == 15))]

In [139]:
df

,year,month,day,date,date.1,open,high,low,close,volume,...,day_name,max,min,difference,candle_body,high_shadow,low_shadow,low-open,high-open,trend
date,,,,,,,,,,,,,,,,,,,,,
2024-01-01 09:16:00+05:30,2024,1,1,2024-01-01 09:16:00+05:30,2024-01-01 09:16:00+05:30,21711.50,21720.00,21695.35,21695.65,0,...,Monday,21720.00,21695.35,24.65,15.85,8.50,-0.30,-16.15,8.50,UP
2024-01-01 09:17:00+05:30,2024,1,1,2024-01-01 09:17:00+05:30,2024-01-01 09:17:00+05:30,21697.70,21711.75,21694.75,21709.55,0,...,Monday,21711.75,21694.75,17.00,-11.85,2.20,-2.95,-2.95,14.05,DOWN
2024-01-01 09:18:00+05:30,2024,1,1,2024-01-01 09:18:00+05:30,2024-01-01 09:18:00+05:30,21709.55,21712.50,21698.40,21699.55,0,...,Monday,21712.50,21698.40,14.10,10.00,2.95,-1.15,-11.15,2.95,UP
2024-01-01 09:19:00+05:30,2024,1,1,2024-01-01 09:19:00+05:30,2024-01-01 09:19:00+05:30,21704.35,21708.00,21693.55,21693.75,0,...,Monday,21708.00,21693.55,14.45,10.60,3.65,-0.20,-10.80,3.65,UP
2024-01-01 09:20:00+05:30,2024,1,1,2024-01-01 09:20:00+05:30,2024-01-01 09:20:00+05:30,21693.90,21701.05,21686.05,21687.90,0,...,Monday,21701.05,21686.05,15.00,6.00,7.15,-1.85,-7.85,7.15,UP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-28 09:55:00+05:30,2024,8,28,2024-08-28 09:55:00+05:30,2024-08-28 09:55:00+05:30,25015.30,25021.85,25013.00,25017.10,0,...,Wednesday,25021.85,25013.00,8.85,-1.80,4.75,-2.30,-2.30,6.55,DOWN
2024-08-28 09:56:00+05:30,2024,8,28,2024-08-28 09:56:00+05:30,2024-08-28 09:56:00+05:30,25016.60,25017.05,25008.50,25009.85,0,...,Wednesday,25017.05,25008.50,8.55,6.75,0.45,-1.35,-8.10,0.45,UP
2024-08-28 09:57:00+05:30,2024,8,28,2024-08-28 09:57:00+05:30,2024-08-28 09:57:00+05:30,25010.20,25012.55,25008.55,25009.70,0,...,Wednesday,25012.55,25008.55,4.00,0.50,2.35,-1.15,-1.65,2.35,UP
2024-08-28 09:58:00+05:30,2024,8,28,2024-08-28 09:58:00+05:30,2024-08-28 09:58:00+05:30,25009.95,25021.35,25009.05,25018.50,0,...,Wednesday,25021.35,25009.05,12.30,-8.55,2.85,-0.90,-0.90,11.40,DOWN
2024-08-28 09:59:00+05:30,2024,8,28,2024-08-28 09:59:00+05:30,2024-08-28 09:59:00+05:30,25017.90,25025.75,25017.05,25023.10,0,...,Wednesday,25025.75,25017.05,8.70,-5.20,2.65,-0.85,-0.85,7.85,DOWN

In [140]:
df['next_trend'] = df['trend'].shift(-1)
df['UPPER_SL'] = df['high'].shift(-1).combine(df['high'], max)
df['LOWER_SL'] = df['low'].shift(-1).combine(df['low'], min)

# Filter rows where the current trend is not equal to the next trend (reciprocal trends)
# reciprocal_pairs = df[df['trend'] != df['next_trend']].iloc[:-1]  # Remove the last row (since it has no "next" row)

# Display the reciprocal trends (current and next rows)
# print(reciprocal_pairs[['date', 'trend', 'next_trend']])

/tmp/ipykernel_3457/1604468191.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['next_trend'] = df['trend'].shift(-1)
/tmp/ipykernel_3457/1604468191.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UPPER_SL'] = df['high'].shift(-1).combine(df['high'], max)
/tmp/ipykernel_3457/1604468191.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['LOWER_SL'] = df['low'].shift(-1).combine(df['low'], min)

In [141]:
final_output = []
for _, group in df.groupby(by=['year','month','day']):
    sub_output = {}
    first_reciprocal_pair_index = group[group['trend'] != group['next_trend']].index[0]
    filtered_df = group.loc[first_reciprocal_pair_index:]
    high = filtered_df.iloc[0]['UPPER_SL']
    low = filtered_df.iloc[0]['LOWER_SL']
    sub_output['year'] = filtered_df.iloc[0]['year']
    sub_output['month'] = filtered_df.iloc[0]['month']
    sub_output['day'] = filtered_df.iloc[0]['day']
    sub_output['hour'] = filtered_df.iloc[0]['hour']
    sub_output['minute'] = filtered_df.iloc[0]['minute']
    SL = None
    BUY_TYPE = None
    executed_after_minutes = 0
    sl_after_minutes = 0
    for i in range(1, len(filtered_df)):
        if SL is None:
            close = filtered_df.iloc[i].close
            open = filtered_df.iloc[i].open
            executed_after_minutes += 1
            if close<=low and open>=high:
                sub_output['is-engullfed'] = True
            else:
                if close<=low:
                    SL = low
                    BUY_TYPE = 'PUT'
                elif open>=high:
                    SL = high
                    BUY_TYPE = 'CALL'
                sub_output['sl'] = SL
                sub_output['option-buy'] = BUY_TYPE
            continue

        sl_after_minutes += 1
        if BUY_TYPE == "PUT":
            sub_high = filtered_df.iloc[i].close
            if sub_high >= SL:
                sub_output['status'] = 'LOSE'
                sub_output['sl-hitted'] = sub_high
                sub_output['tred-running-time'] = sl_after_minutes
                sub_output['tred-run-after'] = executed_after_minutes
                break
        elif BUY_TYPE == "CALL":
            sub_low = filtered_df.iloc[i].close
            if sub_low <= SL:
                sub_output['status'] = 'LOSE'
                sub_output['sl-hitted'] = sub_low
                sub_output['tred-running-time'] = sl_after_minutes
                sub_output['tred-run-after'] = executed_after_minutes
                break
    if SL:
        final_output.append(sub_output)

In [142]:
o = pd.DataFrame(final_output)

In [143]:
len(o) == len(o['status']=='LOSE')

True

In [144]:
r = o[o['month']==7]

In [145]:
r

,year,month,day,hour,minute,sl,option-buy,status,sl-hitted,tred-running-time,tred-run-after,is-engullfed
123,2024,7,1,9,16,24019.15,PUT,LOSE,24020.15,1.0,2.0,NaN
124,2024,7,2,9,16,24186.20,PUT,LOSE,24191.45,2.0,4.0,NaN
125,2024,7,3,9,16,24237.65,CALL,LOSE,24230.70,7.0,6.0,NaN
126,2024,7,4,9,16,24343.70,PUT,LOSE,24359.50,2.0,5.0,NaN
127,2024,7,5,9,20,24185.80,PUT,LOSE,24201.50,2.0,10.0,NaN
128,2024,7,8,9,16,24306.80,CALL,LOSE,24306.55,18.0,5.0,NaN
129,2024,7,9,9,16,24372.65,CALL,LOSE,24363.55,7.0,24.0,NaN
130,2024,7,10,9,18,24408.20,CALL,LOSE,24407.90,3.0,8.0,NaN
131,2024,7,11,9,19,24353.25,PUT,NaN,NaN,NaN,NaN,NaN
132,2024,7,12,9,16,24381.15,PUT,LOSE,24383.95,6.0,2.0,NaN
133,2024,7,15,9,16,24560.85,PUT,LOSE,24569.25,1.0,2.0,NaN
134,2024,7,16,9,16,24616.20,PUT,LOSE,24618.80,2.0,2.0,NaN
135,2024,7,18,9,16,24555.70,PUT,LOSE,24556.00,1.0,4.0,NaN
136,2024,7,19,9,17,24742.95,PUT,LOSE,24746.05,5.0,2.0,NaN
137,2024,7,22,9,16,24422.40,CALL,NaN,NaN,NaN,NaN,NaN
138,2024,7,23,9,20,24528.25,PUT,LOSE,24538.40,1.0,2.0,NaN
139,2024,7,24,9,16,24452.05,CALL,LOSE,24449.30,10.0,3.0,NaN
140,2024,7,25,9,16,24227.45,PUT,LOSE,24249.30,2.0,5.0,NaN
141,2024,7,26,9,16,24473.50,CALL,LOSE,24470.90,8.0,6.0,NaN
142,2024,7,29,9,16,24944.70,PUT,NaN,NaN,NaN,NaN,NaN
143,2024,7,30,9,16,24849.90,CALL,LOSE,24829.70,15.0,17.0,NaN
144,2024,7,31,9,16,24917.45,CALL,LOSE,24905.15,1.0,13.0,NaN