In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('nifty_15m_august_2024.csv')
df.index = pd.to_datetime(df.index)

In [3]:
import mplfinance as mpf

In [4]:
filtered_df = df[df['hour'].isin([9,10,11])]

In [5]:
filtered_df

,datetime,open,high,low,close,adj close,volume,year,month,hour,day,day_name,minute,max,min,difference,candle_body,high_shadow,low_shadow,trend
1970-01-01 00:00:00.000000000,2024-08-01 09:15:00,25030.949219,25077.300781,25012.500000,25054.050781,25054.050781,0,2024,8,9,1,Thursday,15,25077.300781,25012.500000,64.800781,-23.101562,46.351562,41.550781,DOWN
1970-01-01 00:00:00.000000001,2024-08-01 09:30:00,25053.400391,25064.349609,25044.150391,25046.400391,25046.400391,0,2024,8,9,1,Thursday,30,25064.349609,25044.150391,20.199219,7.000000,10.949219,2.250000,UP
1970-01-01 00:00:00.000000002,2024-08-01 09:45:00,25045.550781,25059.000000,25026.199219,25052.849609,25052.849609,0,2024,8,9,1,Thursday,45,25059.000000,25026.199219,32.800781,-7.298828,13.449219,26.650391,DOWN
1970-01-01 00:00:00.000000003,2024-08-01 10:00:00,25053.550781,25056.599609,25034.050781,25037.099609,25037.099609,0,2024,8,10,1,Thursday,0,25056.599609,25034.050781,22.548828,16.451172,3.048828,3.048828,UP
1970-01-01 00:00:00.000000004,2024-08-01 10:15:00,25037.050781,25052.150391,25021.300781,25021.300781,25021.300781,0,2024,8,10,1,Thursday,15,25052.150391,25021.300781,30.849609,15.750000,15.099609,0.000000,UP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970-01-01 00:00:00.000000506,2024-08-30 10:45:00,25224.750000,25227.699219,25214.050781,25224.699219,25224.699219,0,2024,8,10,30,Friday,45,25227.699219,25214.050781,13.648438,0.050781,2.949219,10.648438,UP
1970-01-01 00:00:00.000000507,2024-08-30 11:00:00,25224.449219,25246.650391,25220.400391,25239.099609,25239.099609,0,2024,8,11,30,Friday,0,25246.650391,25220.400391,26.250000,-14.650391,22.201172,18.699219,DOWN
1970-01-01 00:00:00.000000508,2024-08-30 11:15:00,25238.400391,25247.550781,25217.750000,25229.449219,25229.449219,0,2024,8,11,30,Friday,15,25247.550781,25217.750000,29.800781,8.951172,9.150391,11.699219,UP
1970-01-01 00:00:00.000000509,2024-08-30 11:30:00,25229.050781,25240.500000,25225.099609,25225.099609,25225.099609,0,2024,8,11,30,Friday,30,25240.500000,25225.099609,15.400391,3.951172,11.449219,0.000000,UP
1970-01-01 00:00:00.000000510,2024-08-30 11:45:00,25226.050781,25250.550781,25224.000000,25240.199219,25240.199219,0,2024,8,11,30,Friday,45,25250.550781,25224.000000,26.550781,-14.148438,24.500000,16.199219,DOWN

In [6]:
august_dfs = [group for _, group in filtered_df[['year','month','day','open','high','low','close']].groupby('day')]

In [7]:
len(august_dfs)

21

In [8]:
import os

In [9]:
for august_df in august_dfs:
# Plot candlestick chart
    directory_path = f"{os.getcwd()}/{str(df['year'].iloc[0])}_{str(df['month'].iloc[0])}/15m_candlistic"
    if not os.path.exists(directory_path):
        os.makedirs(directory_path)
    mpf.plot(august_df, type='candle', style='charles', title='Candlestick Chart', ylabel='Price', savefig=os.path.join(directory_path,str(august_df['day'].iloc[0])))