In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('nifty_30m_august_2024.csv')
df.index = pd.to_datetime(df.index)

In [3]:
import mplfinance as mpf

In [4]:
filtered_df = df[df['hour'].isin([9,10,11])]

In [5]:
filtered_df

,datetime,open,high,low,close,adj close,volume,year,month,hour,day,day_name,minute,max,min,difference,candle_body,high_shadow,low_shadow,trend
1970-01-01 00:00:00.000000000,2024-08-01 09:30:00,25053.400391,25064.349609,25026.199219,25052.849609,25052.849609,0,2024,8,9,1,Thursday,30,25064.349609,25026.199219,38.150391,0.550781,10.949219,26.650391,UP
1970-01-01 00:00:00.000000001,2024-08-01 10:00:00,25053.550781,25056.599609,25021.300781,25021.300781,25021.300781,0,2024,8,10,1,Thursday,0,25056.599609,25021.300781,35.298828,32.250000,3.048828,0.000000,UP
1970-01-01 00:00:00.000000002,2024-08-01 10:30:00,25021.650391,25032.300781,25006.000000,25014.400391,25014.400391,0,2024,8,10,1,Thursday,30,25032.300781,25006.000000,26.300781,7.250000,10.650391,8.400391,UP
1970-01-01 00:00:00.000000003,2024-08-01 11:00:00,25014.400391,25041.199219,25004.050781,25022.099609,25022.099609,0,2024,8,11,1,Thursday,0,25041.199219,25004.050781,37.148438,-7.699219,26.798828,18.048828,DOWN
1970-01-01 00:00:00.000000004,2024-08-01 11:30:00,25023.099609,25027.750000,24986.449219,24999.849609,24999.849609,0,2024,8,11,1,Thursday,30,25027.750000,24986.449219,41.300781,23.250000,4.650391,13.400391,UP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970-01-01 00:00:00.000000240,2024-08-30 09:30:00,25252.750000,25256.449219,25206.449219,25225.349609,25225.349609,0,2024,8,9,30,Friday,30,25256.449219,25206.449219,50.000000,27.400391,3.699219,18.900391,UP
1970-01-01 00:00:00.000000241,2024-08-30 10:00:00,25224.900391,25236.650391,25199.699219,25218.599609,25218.599609,0,2024,8,10,30,Friday,0,25236.650391,25199.699219,36.951172,6.300781,11.750000,18.900391,UP
1970-01-01 00:00:00.000000242,2024-08-30 10:30:00,25217.449219,25235.949219,25210.800781,25224.699219,25224.699219,0,2024,8,10,30,Friday,30,25235.949219,25210.800781,25.148438,-7.250000,18.500000,13.898438,DOWN
1970-01-01 00:00:00.000000243,2024-08-30 11:00:00,25224.449219,25247.550781,25217.750000,25229.449219,25229.449219,0,2024,8,11,30,Friday,0,25247.550781,25217.750000,29.800781,-5.000000,23.101562,11.699219,DOWN
1970-01-01 00:00:00.000000244,2024-08-30 11:30:00,25229.050781,25250.550781,25224.000000,25240.199219,25240.199219,0,2024,8,11,30,Friday,30,25250.550781,25224.000000,26.550781,-11.148438,21.500000,16.199219,DOWN

In [6]:
august_dfs = [group for _, group in filtered_df[['year','month','day','open','high','low','close']].groupby('day')]

In [7]:
len(august_dfs)

21

In [8]:
import os

In [9]:
for august_df in august_dfs:
# Plot candlestick chart
    directory_path = f"{os.getcwd()}/{str(df['year'].iloc[0])}_{str(df['month'].iloc[0])}/30m_candlistic"
    if not os.path.exists(directory_path):
        os.makedirs(directory_path)
    mpf.plot(august_df, type='candle', style='charles', title='Candlestick Chart', ylabel='Price', savefig=os.path.join(directory_path,str(august_df['day'].iloc[0])))