In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('nifty_5m_august_2024.csv')
df.index = pd.to_datetime(df.index)

In [3]:
import mplfinance as mpf

In [4]:
filtered_df = df[df['hour'].isin([9,10,11])]

In [5]:
filtered_df

,datetime,open,high,low,close,adj close,volume,year,month,hour,day,day_name,max,min,difference,candle_body,high_shadow,low_shadow,trend
1970-01-01 00:00:00.000000000,2024-08-01 09:15:00+05:30,25030.949219,25054.300781,25012.500000,25053.150391,25053.150391,0,2024,8,9,1,Thursday,25054.300781,25012.500000,41.800781,-22.201172,23.351562,40.650391,DOWN
1970-01-01 00:00:00.000000001,2024-08-01 09:20:00+05:30,25054.050781,25077.300781,25049.400391,25058.250000,25058.250000,0,2024,8,9,1,Thursday,25077.300781,25049.400391,27.900391,-4.199219,23.250000,8.849609,DOWN
1970-01-01 00:00:00.000000002,2024-08-01 09:25:00+05:30,25058.750000,25063.050781,25050.800781,25054.050781,25054.050781,0,2024,8,9,1,Thursday,25063.050781,25050.800781,12.250000,4.699219,4.300781,3.250000,UP
1970-01-01 00:00:00.000000003,2024-08-01 09:30:00+05:30,25053.400391,25064.000000,25044.900391,25063.900391,25063.900391,0,2024,8,9,1,Thursday,25064.000000,25044.900391,19.099609,-10.500000,10.599609,19.000000,DOWN
1970-01-01 00:00:00.000000004,2024-08-01 09:35:00+05:30,25064.349609,25064.349609,25044.449219,25048.050781,25048.050781,0,2024,8,9,1,Thursday,25064.349609,25044.449219,19.900391,16.298828,0.000000,3.601562,UP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970-01-01 00:00:00.000001528,2024-08-30 11:35:00+05:30,25234.599609,25239.750000,25228.800781,25231.300781,25231.300781,0,2024,8,11,30,Friday,25239.750000,25228.800781,10.949219,3.298828,5.150391,2.500000,UP
1970-01-01 00:00:00.000001529,2024-08-30 11:40:00+05:30,25229.949219,25236.199219,25225.099609,25225.099609,25225.099609,0,2024,8,11,30,Friday,25236.199219,25225.099609,11.099609,4.849609,6.250000,0.000000,UP
1970-01-01 00:00:00.000001530,2024-08-30 11:45:00+05:30,25226.050781,25237.250000,25224.000000,25233.349609,25233.349609,0,2024,8,11,30,Friday,25237.250000,25224.000000,13.250000,-7.298828,11.199219,9.349609,DOWN
1970-01-01 00:00:00.000001531,2024-08-30 11:50:00+05:30,25232.599609,25243.900391,25229.250000,25243.099609,25243.099609,0,2024,8,11,30,Friday,25243.900391,25229.250000,14.650391,-10.500000,11.300781,13.849609,DOWN
1970-01-01 00:00:00.000001532,2024-08-30 11:55:00+05:30,25243.849609,25250.550781,25238.199219,25240.199219,25240.199219,0,2024,8,11,30,Friday,25250.550781,25238.199219,12.351562,3.650391,6.701172,2.000000,UP

In [6]:
august_dfs = [group for _, group in filtered_df[['year','month','day','open','high','low','close']].groupby('day')]

In [7]:
len(august_dfs)

21

In [8]:
import os

In [9]:
for august_df in august_dfs:
# Plot candlestick chart
    directory_path = f"{os.getcwd()}/{str(df['year'].iloc[0])}_{str(df['month'].iloc[0])}/5m_candlistic"
    if not os.path.exists(directory_path):
        os.makedirs(directory_path)
    mpf.plot(august_df, type='candle', style='charles', title='Candlestick Chart', ylabel='Price', savefig=os.path.join(directory_path,str(august_df['day'].iloc[0])))