In [1]:
import pandas as pd

In [2]:
df_5 = pd.read_csv('nifty_5m_september_2024.csv')
df_5.index = pd.to_datetime(df_5.index)

In [3]:
import mplfinance as mpf

In [5]:
df_5
# Taking a first three rows of each day.
df_5 = df_5.groupby(df_5['day']).head(1)
df_5

,datetime,open,high,low,close,adj close,volume,year,month,hour,day,day_name,minute,max,min,difference,candle_body,high_shadow,low_shadow,trend
1970-01-01 00:00:00.000000000,2024-09-02 09:15:00+05:30,25311.599609,25313.349609,25293.050781,25312.949219,25312.949219,0,2024,9,9,2,Monday,15,25313.349609,25293.050781,20.298828,-1.349609,1.750000,19.898438,DOWN
1970-01-01 00:00:00.000000075,2024-09-03 09:15:00+05:30,25313.400391,25317.750000,25258.900391,25272.500000,25272.500000,0,2024,9,9,3,Tuesday,15,25317.750000,25258.900391,58.849609,40.900391,4.349609,13.599609,UP
1970-01-01 00:00:00.000000150,2024-09-04 09:15:00+05:30,25106.699219,25127.849609,25086.550781,25099.900391,25099.900391,0,2024,9,9,4,Wednesday,15,25127.849609,25086.550781,41.298828,6.798828,21.150391,13.349609,UP
1970-01-01 00:00:00.000000225,2024-09-05 09:15:00+05:30,25263.050781,25270.150391,25234.099609,25242.000000,25242.000000,0,2024,9,9,5,Thursday,15,25270.150391,25234.099609,36.050781,21.050781,7.099609,7.900391,UP
1970-01-01 00:00:00.000000300,2024-09-06 09:15:00+05:30,25090.550781,25131.650391,25088.250000,25088.800781,25088.800781,0,2024,9,9,6,Friday,15,25131.650391,25088.250000,43.400391,1.750000,41.099609,0.550781,UP
1970-01-01 00:00:00.000000375,2024-09-09 09:15:00+05:30,24820.949219,24821.550781,24772.949219,24800.500000,24800.500000,0,2024,9,9,9,Monday,15,24821.550781,24772.949219,48.601562,20.449219,0.601562,27.550781,UP
1970-01-01 00:00:00.000000450,2024-09-10 09:15:00+05:30,25003.199219,25011.099609,24967.349609,24974.050781,24974.050781,0,2024,9,9,10,Tuesday,15,25011.099609,24967.349609,43.750000,29.148438,7.900391,6.701172,UP
1970-01-01 00:00:00.000000525,2024-09-11 09:15:00+05:30,25033.750000,25034.099609,25007.750000,25024.449219,25024.449219,0,2024,9,9,11,Wednesday,15,25034.099609,25007.750000,26.349609,9.300781,0.349609,16.699219,UP
1970-01-01 00:00:00.000000600,2024-09-12 09:15:00+05:30,25051.599609,25051.599609,25013.500000,25016.349609,25016.349609,0,2024,9,9,12,Thursday,15,25051.599609,25013.500000,38.099609,35.250000,0.000000,2.849609,UP
1970-01-01 00:00:00.000000675,2024-09-13 09:15:00+05:30,25410.650391,25413.150391,25337.300781,25342.699219,25342.699219,0,2024,9,9,13,Friday,15,25413.150391,25337.300781,75.849609,67.951172,2.500000,5.398438,UP
1970-01-01 00:00:00.000000750,2024-09-16 09:15:00+05:30,25406.650391,25408.900391,25372.449219,25395.300781,25395.300781,0,2024,9,9,16,Monday,15,25408.900391,25372.449219,36.451172,11.349609,2.250000,22.851562,UP

In [7]:
import os

In [12]:
for index, row in df_5.iterrows():
# Plot candlestick chart
    directory_path = f"{os.getcwd()}/{str(row['year'])}_{str(row['month'])}/ohh_analysis"
    if not os.path.exists(directory_path):
        os.makedirs(directory_path)
    
    # Create a DataFrame with OHLC data for a single day
    ohlc_data = pd.DataFrame({
        'Open': [row['open']],
        'High': [row['high']],
        'Low': [row['low']],
        'Close': [row['close']],
        'Volume': [row['volume']]  # Optional, only if volume is available
    }, index=[pd.Timestamp(f"{row['year']}-{row['month']}-{row['day']}")])
    

    mpf.plot(ohlc_data, type='candle', style='charles', title='Candlestick Chart', ylabel='Price', savefig=os.path.join(directory_path,str(row['day'])))